### ISSUE TITLE
RuntimeError: The expanded size of the tensor (8) must match the existing size (0) at non-singleton dimension 1

### ISSUE THREAD

**Issue by Kunika21** [ucbdrive/3d-vehicle-tracking#11]
crashed during running ./run_train.sh .

**Comment by eborboihuc** [comment]
Hi @Kunika21,

From the error message, it might be the problem of missing some data.

Can you provide more details?
1. Have you prepared all the data?
2. Which dataset did you have?
3. What is your procedure to reproduce the error?
4. The full error message
