### ISSUE TITLE
Error in # Step 01 - Generate bounding boxes ./run_test.sh

### ISSUE THREAD

**Issue by OmarElzaafaranyBrightskies** [ucbdrive/3d-vehicle-tracking#12]
Traceback (most recent call last):
  File "test_net.py", line 30, in <module>
    from model.utils.net_utils import save_net, load_net, vis_detections
  File "/content/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/utils/net_utils.py", line 7, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/content/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_crop/functions/roi_crop.py", line 3, in <module>
    from .._ext import roi_crop
  File "/content/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ImportError: /content/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: __cudaPopCallConfiguration

root : 200_14_18895 Finish!
Copy output pkl file to dataset folder...
cp: cannot stat 'vis/faster_rcnn_200_14_18895/detections_val.pkl': No such file or directory
Done!!

**Comment by F0Wen** [comment]
did you solve it?

**Comment by OmarElzaafaranyBrightskies** [comment]
No, I haven't solved it yet.

**Comment by eborboihuc** [comment]
Hi all,

I could run the code smoothly from my end. I think it might come from the failure of compiling the code in `src/` with a wrong CUDA version. 

You may want to take a look at the thread [here](https://github.com/jwyang/faster-rcnn.pytorch/issues/190), where they faced the same error `_roi_crop.so: undefined symbol: __cudaPopCallConfiguration`. Please use CUDA 9.0 to compile their faster-rcnn `src` files.

Could you please check the output of the following script with CUDA 9.0?
```bash
cd faster-rcnn.pytorch
bash init.sh
```

I'll close this thread for now. If using CUDA 9.0 cannot solve your problem, please feel free to re-open this issue.
