### ISSUE TITLE
tensor (8) must match the existing size (0)

### ISSUE THREAD

**Issue by biexiangduo** [ucbdrive/3d-vehicle-tracking#16]
hello ,
when I run "./run_train.sh ",error came:
(base) pf@pf-System-Product-Name:~/3d-vehicle-tracking/faster-rcnn.pytorch$ ./run_train.sh 
Called with args:
Namespace(batch_size=8, checkepoch=1, checkpoint=0, checkpoint_interval=10000, checksession=1, class_agnostic=False, cuda=True, dataset='gta_det', disp_interval=100, large_scale=False, lr=0.001, lr_decay_gamma=0.1, lr_decay_step=10, mGPUs=True, max_epochs=20, net='res101', num_workers=4, optimizer='adam', resume=False, save_dir='models', session=201, start_epoch=1, use_tfboard=False)
/home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/utils/config.py:384: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = edict(yaml.load(f))
Using config:
{'ANCHOR_RATIOS': [0.5, 1, 2],
 'ANCHOR_SCALES': [2, 4, 8, 16],
 'ANNO_PATH': 'train',
 'BINARY_CLASS': True,
 'CROP_RESIZE_WITH_MAX_POOL': False,
 'CUDA': False,
 'DATASET': 'gta',
 'DATA_DIR': '/home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'res101',
 'FEAT_STRIDE': [16],
 'FOCAL': 935.3074360871937,
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MAX_NUM_GT_BOXES': 100,
 'MOBILENET': {'DEPTH_MULTIPLIER': 1.0,
               'FIXED_LAYERS': 5,
               'REGU_DEPTH': False,
               'WEIGHT_DECAY': 4e-05},
 'PIXEL_MEANS': array([[[102.9801, 115.9465, 122.7717]]]),
 'POOLING_MODE': 'align',
 'POOLING_SIZE': 7,
 'RESNET': {'FIXED_BLOCKS': 1, 'MAX_POOL': False},
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/pf/3d-vehicle-tracking/faster-rcnn.pytorch',
 'RUN_POSE': True,
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1920,
          'MODE': 'nms',
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'gt',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'RPN_TOP_N': 5000,
          'SCALES': [1080],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': False,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'BIAS_DECAY': False,
           'BN_TRAIN': False,
           'DISPLAY': 20,
           'DOUBLE_BIAS': False,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'LEARNING_RATE': 0.001,
           'MAX_SIZE': 1920,
           'MOMENTUM': 0.9,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 8,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [1080],
           'SNAPSHOT_ITERS': 5000,
           'SNAPSHOT_KEPT': 3,
           'SNAPSHOT_PREFIX': 'res101_faster_rcnn',
           'STEPSIZE': [30000],
           'SUMMARY_INTERVAL': 180,
           'TRIM_HEIGHT': 1080,
           'TRIM_WIDTH': 1920,
           'TRUNCATED': False,
           'USE_ALL_GT': True,
           'USE_FLIPPED': False,
           'USE_GT': False,
           'WEIGHT_DECAY': 0.0001},
 'USE_DEBUG_SET': False,
 'USE_GPU_NMS': True}
Loaded dataset `gta_det_train` for training
Set proposal method: gt
Preparing training data...
done
before filtering, there are 0 images...
after filtering, there are 0 images...
0 roidb entries
Loading pretrained weights from data/pretrained_model/resnet101_caffe.pth
Traceback (most recent call last):
  File "trainval_net.py", line 363, in <module>
    data_iter = iter(dataloader)
  File "/home/pf/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "/home/pf/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 297, in __init__
    self._put_indices()
  File "/home/pf/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in _put_indices
    indices = next(self.sample_iter, None)
  File "/home/pf/.local/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 138, in __iter__
    for idx in self.sampler:
  File "trainval_net.py", line 137, in __iter__
    self.batch_size) + self.range
RuntimeError: The expanded size of the tensor (8) must match the existing size (0) at non-singleton dimension 1

--------------------------------------------------
so I searched in the issues,and check my datasets .datasets is complete.
is it the wrong configuration in cuda?
by the way ,the following is my configuration information:

 (base) pf@pf-System-Product-Name:~/3d-vehicle-tracking/faster-rcnn.pytorch$ bash init.sh
++ pwd
+ _PWD=/home/pf/3d-vehicle-tracking/faster-rcnn.pytorch
+ _DATA_GTA=/home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/../3d-tracking/data/gta5_tracking/
+ _DATA_KITTI_T=/home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/../3d-tracking/data/kitti_tracking/
+ _DATA_KITTI_D=/home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/../3d-tracking/data/kitti_object/
+ cd lib/
+ ./make.sh
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
Including CUDA code.
/home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/nms
['/home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/nms/src/nms_cuda_kernel.cu.o']
generating /tmp/tmp7dsxa0xo/_nms.c
setting the current directory to '/tmp/tmp7dsxa0xo'
running build_ext
building '_nms' extension
creating home
creating home/pf
creating home/pf/3d-vehicle-tracking
creating home/pf/3d-vehicle-tracking/faster-rcnn.pytorch
creating home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib
creating home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model
creating home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_pooling
creating home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_pooling/src
gcc -pthread -B /home/pf/anaconda3/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/pf/anaconda3/include/python3.6m -c _roi_pooling.c -o ./_roi_pooling.o -std=c99
gcc -pthread -B /home/pf/anaconda3/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/pf/anaconda3/include/python3.6m -c /home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_pooling/src/roi_pooling.c -o ./home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_pooling/src/roi_pooling.o -std=c99
gcc -pthread -B /home/pf/anaconda3/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/pf/anaconda3/include/python3.6m -c /home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_pooling/src/roi_pooling_cuda.c -o ./home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_pooling/src/roi_pooling_cuda.o -std=c99
gcc -pthread -shared -B /home/pf/anaconda3/compiler_compat -L/home/pf/anaconda3/lib -Wl,-rpath=/home/pf/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ -std=c99 ./_roi_pooling.o ./home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_pooling/src/roi_pooling.o ./home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_pooling/src/roi_pooling_cuda.o /home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_pooling/src/roi_pooling.cu.o -o ./_roi_pooling.so
Compiling roi align kernels by nvcc...
/home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_align
Including CUDA code.
generating /tmp/tmpkageu3dg/_roi_align.c
setting the current directory to '/tmp/tmpkageu3dg'
running build_ext
building '_roi_align' extension
creating home
creating home/pf
creating home/pf/3d-vehicle-tracking
creating home/pf/3d-vehicle-tracking/faster-rcnn.pytorch
creating home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib
creating home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model
creating home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_align
creating home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_align/src
gcc -pthread -B /home/pf/anaconda3/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/pf/anaconda3/include/python3.6m -c _roi_align.c -o ./_roi_align.o -std=c99
gcc -pthread -B /home/pf/anaconda3/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/pf/anaconda3/include/python3.6m -c /home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c -o ./home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.o -std=c99
gcc -pthread -B /home/pf/anaconda3/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/pf/anaconda3/include/python3.6m -c /home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align_cuda.c -o ./home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align_cuda.o -std=c99
gcc -pthread -shared -B /home/pf/anaconda3/compiler_compat -L/home/pf/anaconda3/lib -Wl,-rpath=/home/pf/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ -std=c99 ./_roi_align.o ./home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.o ./home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align_cuda.o /home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align_kernel.cu.o -o ./_roi_align.so
Compiling roi crop kernels by nvcc...
Including CUDA code.
/home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_crop
generating /tmp/tmppw9uiuk4/_roi_crop.c
setting the current directory to '/tmp/tmppw9uiuk4'
running build_ext
building '_roi_crop' extension
creating home
creating home/pf
creating home/pf/3d-vehicle-tracking
creating home/pf/3d-vehicle-tracking/faster-rcnn.pytorch
creating home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib
creating home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model
creating home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_crop
creating home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_crop/src
gcc -pthread -B /home/pf/anaconda3/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/pf/anaconda3/include/python3.6m -c _roi_crop.c -o ./_roi_crop.o -std=c99
gcc -pthread -B /home/pf/anaconda3/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/pf/anaconda3/include/python3.6m -c /home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.c -o ./home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.o -std=c99
gcc -pthread -B /home/pf/anaconda3/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/pf/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/pf/anaconda3/include/python3.6m -c /home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop_cuda.c -o ./home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop_cuda.o -std=c99
gcc -pthread -shared -B /home/pf/anaconda3/compiler_compat -L/home/pf/anaconda3/lib -Wl,-rpath=/home/pf/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ -std=c99 ./_roi_crop.o ./home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.o ./home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop_cuda.o /home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop_cuda_kernel.cu.o -o ./_roi_crop.so
+ cd /home/pf/3d-vehicle-tracking/faster-rcnn.pytorch
+ mkdir -p data/pretrained_model
+ cd data/pretrained_model
+ wget https://s3.amazonaws.com/pytorch/models/resnet101-5d3b4d8f.pth
--2019-11-28 06:46:12--  https://s3.amazonaws.com/pytorch/models/resnet101-5d3b4d8f.pth
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.26.70
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.26.70|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 178728960 (170M) [application/octet-stream]
Saving to: ‘resnet101-5d3b4d8f.pth’

resnet101-5d3b4d8f.pth      100%[========================================>] 170.45M  1.57MB/s    in 1m 54s  

2019-11-28 06:48:08 (1.50 MB/s) - ‘resnet101-5d3b4d8f.pth’ saved [178728960/178728960]

+ mv resnet101-5d3b4d8f.pth resnet101_caffe.pth
+ cd /home/pf/3d-vehicle-tracking/faster-rcnn.pytorch
+ cd data/
+ ln -s /home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/../3d-tracking/data/gta5_tracking/ gta5_tracking
+ echo 'mv GTA dataset (train, val, test) to data/gta5_tracking'
mv GTA dataset (train, val, test) to data/gta5_tracking
+ cd /home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/data/
+ ln -s /home/pf/3d-vehicle-tracking/faster-rcnn.pytorch/../3d-tracking/data/kitti_tracking/ kitti_tracking
+ echo 'mv KITTI tracking dataset (train, test) to data/kitti_tracking'
mv KITTI tracking dataset (train, test) to data/kitti_tracking
+ cd /home/pf/3d-vehicle-tracking/faster-rcnn.pytorch
+ mkdir vis/
+ mkdir -p models/res101/gta_det/
+ mkdir models/res101/kitti/
+ echo 'Please move faster_rcnn_200_14_18895.pth to models/res101/gta_det/'
Please move faster_rcnn_200_14_18895.pth to models/res101/gta_det/
+ echo 'Please move faster_rcnn_300_100_175.pth to models/res101/kitti/'
Please move faster_rcnn_300_100_175.pth to models/res101/kitti/
-----------------i do not understand when i run the upper command,show this commands.should I execute this commands?---------------------

system :ubuntu16.04
gpu:1080ti

**Comment by eborboihuc** [comment]
Hi,

So there're two questions as follow:

> when I run "./run_train.sh ",error came:
...
Preparing training data...
done
before filtering, there are 0 images...
after filtering, there are 0 images...
0 roidb entries
...


I think the problem would come from the dataset
From my end, the training data consist of `447695` entries 
```bash
Preparing training data...
done
before filtering, there are 457906 images...
after filtering, there are 447695 images...
447695 roidb entries
```

Please check again if you prepared all the data [[link](https://github.com/ucbdrive/3d-vehicle-tracking#data-preparation)]
```bash
data/
data/gta5_tracking/
data/gta5_tracking/val/
data/gta5_tracking/test/
data/gta5_tracking/train/
data/gta5_tracking/train/image/
data/gta5_tracking/train/label/
data/gta5_tracking/train/image/rec_10081640_thunder_14h48m_x-173y-1504tox2266y1183/1539042031264_final.jpg
...
data/gta5_tracking/train/label/rec_10081640_thunder_14h48m_x-173y-1504tox2266y1183.json
...
```

And the second question is
> echo 'Please move faster_rcnn_200_14_18895.pth to models/res101/gta_det/'
Please move faster_rcnn_200_14_18895.pth to models/res101/gta_det/
echo 'Please move faster_rcnn_300_100_175.pth to models/res101/kitti/'
Please move faster_rcnn_300_100_175.pth to models/res101/kitti/
-----------------i do not understand when i run the upper command,show this commands.should I execute this commands?---------------------

Yes, please directly download the files and place them accordingly.
```bash
// under 3d-tracking/
python loader/download.py checkpoint
// you may find the `faster_rcnn_checkpoint.zip` under `./data/zip/`
// Unzip them and place them to the folder accordingly
```
