### ISSUE TITLE
Run KITTI test error: FileNotFound

### ISSUE THREAD

**Issue by chrisHuxi** [ucbdrive/3d-vehicle-tracking#17]
Hi,

Thanks for sharing your impressive job.

I'm trying to reproduce your result on **KITTI test** dataset.
But when I run : 
`PYTHONPATH=. python loader/gen_dataset.py kitti test --kitti_task track`

I got this error:
`
FileNotFoundError: [Errno 2] No such file or directory: '/media/huxi/DATA/inf_master/Semester-4/lecture/absolute/code/JM3DDT/3d-vehicle-tracking/3d-tracking/data/kitti_tracking/testing/label_02/0000/000000.json'
`
But as I know, the KITTI didn't offer the label for test label, label_02 usually means label for training data.

And I also checked the detection file (**kitti_test_trk_detections_RRC.pkl**), it seems result from faster-rcnn, so how can we convert it into json type?

Thank you!

**Comment by freetown113** [comment]
Hi, 
     I've got a strange error: first epoch pass without any remarkable problem, but while data is preparing for the second one segmentation fault appear while execute line 139 in "3d-vehicle-tracking/faster-rcnn.pytorch/trainval_net.py" -> class sampler(Sampler): -> self.rand_num_view = self.rand_num.view(-1). Bizarre, it didn't cause any fault before first epoch.
Do you have any suggestion?

Thank you!

**Comment by eborboihuc** [comment]
Hi @chrisHuxi,

I cannot reproduce the issue from my end.

```bash
>> PYTHONPATH=. python loader/gen_dataset.py kitti test --kitti_task track --mode test
Load label file from path: ~/Workspace/3d-vehicle-tracking-release/3d-tracking/data/kitti_tracking/testing/label_02
Sequence 0: Data length: 0, Valid data length: 0
Sequence 1: Data length: 0, Valid data length: 0
Sequence 2: Data length: 0, Valid data length: 0
Sequence 3: Data length: 0, Valid data length: 0
Sequence 4: Data length: 0, Valid data length: 0
Sequence 5: Data length: 0, Valid data length: 0
Sequence 6: Data length: 0, Valid data length: 0
Sequence 7: Data length: 0, Valid data length: 0
Sequence 8: Data length: 0, Valid data length: 0
Sequence 9: Data length: 0, Valid data length: 0
Sequence 10: Data length: 0, Valid data length: 0
Sequence 11: Data length: 0, Valid data length: 0
Sequence 12: Data length: 0, Valid data length: 0
Sequence 13: Data length: 0, Valid data length: 0
Sequence 14: Data length: 0, Valid data length: 0
Sequence 15: Data length: 0, Valid data length: 0
Sequence 16: Data length: 0, Valid data length: 0
Sequence 17: Data length: 0, Valid data length: 0
Sequence 18: Data length: 0, Valid data length: 0
Sequence 19: Data length: 0, Valid data length: 0
Sequence 20: Data length: 0, Valid data length: 0
Sequence 21: Data length: 0, Valid data length: 0
Sequence 22: Data length: 0, Valid data length: 0
Sequence 23: Data length: 0, Valid data length: 0
Sequence 24: Data length: 0, Valid data length: 0
Sequence 25: Data length: 0, Valid data length: 0
Sequence 26: Data length: 0, Valid data length: 0
Sequence 27: Data length: 0, Valid data length: 0
Sequence 28: Data length: 0, Valid data length: 0
Overall Data length 0 Valid data length 0
Data preparation done!!
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Empty data
Saving ~/Workspace/3d-vehicle-tracking-release/3d-tracking/data/kitti_tracking/kitti_test_trk_list.json with 29 sequences...
Saved
```

If you prepared all the folders, it would be easy to generate all the files you need with `PYTHONPATH=. python loader/gen_dataset.py kitti test --kitti_task track`.

The structure of the folders would be under the `3d-tracking/data/kitti_tracking/testing/` like the following:
```bash
calib/
calib/0000.txt
...
image_02/
image_02/0000/
...
label_02/
label_02/0000/
...
oxts/0000.txt
...
```

For each generated file, it would have an empty `labels` entry.
```python
{"name": "0000/000000.png", "videoName": "0000", "resolution": {"width": 1248, "height": 384}, "intrinsics": {"focal": [721.5377197265625, 721.5377197265625], "center": [609.559326171875, 172.85400390625],     "fov": 60, "nearClip": -1, "cali": [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0    , 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257]]}, "extrinsics": {"location": [0.0, 0.0, 0.0], "rotation": [0.036638, 0.013684, 1.3010823267949]}, "timestamp": 0, "frameIndex": 0, "labels": []}
```

**Comment by eborboihuc** [comment]
> Hi,
> I've got a strange error: first epoch pass without any remarkable problem, but while data is preparing for the second one segmentation fault appear while execute line 139 in "3d-vehicle-tracking/faster-rcnn.pytorch/trainval_net.py" -> class sampler(Sampler): -> self.rand_num_view = self.rand_num.view(-1). Bizarre, it didn't cause any fault before first epoch.
> Do you have any suggestion?
> 
> Thank you!

Hi, @freetown113,

I do not have a simple solution directly from your description. It would be better to open a new issue and post your error message there so that others can get an answer (or provide you one) if they faced the same problem.

**Comment by chrisHuxi** [comment]
> Hi @chrisHuxi,
> 
> I cannot reproduce the issue from my end.
> 
> ```shell
> >> PYTHONPATH=. python loader/gen_dataset.py kitti test --kitti_task track --mode test
> Load label file from path: ~/Workspace/3d-vehicle-tracking-release/3d-tracking/data/kitti_tracking/testing/label_02
> Sequence 0: Data length: 0, Valid data length: 0
> Sequence 1: Data length: 0, Valid data length: 0
> Sequence 2: Data length: 0, Valid data length: 0
> Sequence 3: Data length: 0, Valid data length: 0
> Sequence 4: Data length: 0, Valid data length: 0
> Sequence 5: Data length: 0, Valid data length: 0
> Sequence 6: Data length: 0, Valid data length: 0
> Sequence 7: Data length: 0, Valid data length: 0
> Sequence 8: Data length: 0, Valid data length: 0
> Sequence 9: Data length: 0, Valid data length: 0
> Sequence 10: Data length: 0, Valid data length: 0
> Sequence 11: Data length: 0, Valid data length: 0
> Sequence 12: Data length: 0, Valid data length: 0
> Sequence 13: Data length: 0, Valid data length: 0
> Sequence 14: Data length: 0, Valid data length: 0
> Sequence 15: Data length: 0, Valid data length: 0
> Sequence 16: Data length: 0, Valid data length: 0
> Sequence 17: Data length: 0, Valid data length: 0
> Sequence 18: Data length: 0, Valid data length: 0
> Sequence 19: Data length: 0, Valid data length: 0
> Sequence 20: Data length: 0, Valid data length: 0
> Sequence 21: Data length: 0, Valid data length: 0
> Sequence 22: Data length: 0, Valid data length: 0
> Sequence 23: Data length: 0, Valid data length: 0
> Sequence 24: Data length: 0, Valid data length: 0
> Sequence 25: Data length: 0, Valid data length: 0
> Sequence 26: Data length: 0, Valid data length: 0
> Sequence 27: Data length: 0, Valid data length: 0
> Sequence 28: Data length: 0, Valid data length: 0
> Overall Data length 0 Valid data length 0
> Data preparation done!!
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Empty data
> Saving ~/Workspace/3d-vehicle-tracking-release/3d-tracking/data/kitti_tracking/kitti_test_trk_list.json with 29 sequences...
> Saved
> ```
> 
> If you prepared all the folders, it would be easy to generate all the files you need with `PYTHONPATH=. python loader/gen_dataset.py kitti test --kitti_task track`.
> 
> The structure of the folders would be under the `3d-tracking/data/kitti_tracking/testing/` like the following:
> 
> ```shell
> calib/
> calib/0000.txt
> ...
> image_02/
> image_02/0000/
> ...
> label_02/
> label_02/0000/
> ...
> oxts/0000.txt
> ...
> ```
> 
> For each generated file, it would have an empty `labels` entry.
> 
> ```python
> {"name": "0000/000000.png", "videoName": "0000", "resolution": {"width": 1248, "height": 384}, "intrinsics": {"focal": [721.5377197265625, 721.5377197265625], "center": [609.559326171875, 172.85400390625],     "fov": 60, "nearClip": -1, "cali": [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0    , 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257]]}, "extrinsics": {"location": [0.0, 0.0, 0.0], "rotation": [0.036638, 0.013684, 1.3010823267949]}, "timestamp": 0, "frameIndex": 0, "labels": []}
> ```

Thanks for replying, after creating corresponding empty folder (0000,0001,etc) in label_02 folder, everything goes all right. : )
