### ISSUE TITLE
gen_dataset.py fails with processing GTA data

### ISSUE THREAD

**Issue by jackkwok** [ucbdrive/3d-vehicle-tracking#20]
I need to regenerate the dataset because my dataset is stored on a different path.  gen_dataset.gta_label expects the key 'dset_name' in the label JSON.  But the JSON doesn't have such a key.  Looks like a bug?

Sample GTA label JSON:
`{"name": "rec_10090911_clouds_21h53m_x-968y-1487tox2523y214/1539101548424_final.jpg", "videoName": "rec_10090911_clouds_21h53m_x-968y-1487tox2523y214", "reso
lution": {"width": 1920, "height": 1080}, "attributes": {"weather": "clouds", "scene": "undefined", "timeofday": "night"}, "intrinsics": {"focal": [935.30743
60871937, 935.3074360871937], "center": [960, 540], "fov": 60.0, "nearClip": 0.15, "cali": [[935.3074360871937, 0, 960, 0], [0, 935.3074360871937, 540, 0], [
0, 0, 1, 0]]}, "extrinsics": {"location": [542.5374139999999, 638.261108, 24.595841999999998], "rotation": [0.07860163590185047, 0.04926174360461475, -1.5720
14182640353]}, "timestamp": 1539101548424, "frameIndex": 267, "labels": [{"id": 312067, "category": "Car", "manualShape": false, "manualAttributes": false, "
attributes": {"occluded": 1, "truncated": 0, "ignore": false}, "box2d": {"x1": 1344, "y1": 582, "x2": 1507, "y2": 625, "confidence": 1.0}, "box3d": {"alpha":
 2.6717959948834453, "orientation": 3.1285669162153136, "location": [13.92370725222956, 1.9204142545872491, 28.332843371904413], "dimension": [1.414723087054
686, 1.986859393486255, 5.1919703417856296]}}, {"id": 346115, "category": "Car", "manualShape": false, "manualAttributes": false, "attributes": {"occluded": 
1, "truncated": 2, "ignore": false}, "box2d": {"x1": 0, "y1": 672, "x2": 216, "y2": 822, "confidence": 1.0}, "box3d": {"alpha": -0.7139769182849092, "orienta
tion": -1.5710088270105829, "location": [-6.546893716188748, 1.1920684201530107, 5.670235020892589], "dimension": [1.4147235458536747, 1.9867095159721255, 5.
191999838206263]}}]}`

**Comment by eborboihuc** [comment]
Hi @jackkwok, have your problem solved?

Unfortunately, the raw annotation of GTA is not available publicly. However, `dset_name` is basically the same as 'video_name'. It's `"rec_10090911_clouds_21h53m_x-968y-1487tox2523y214"`.

> I need to regenerate the dataset because my dataset is stored on a different path.

If you have the need to store your dataset on a different path, I would suggest you make a soft link of the dataset to the same path under `3d-vehicle-tracking/blob/master/3d-tracking/data/`. Then you can continue the use of our repo without a problem.
