### ISSUE TITLE
run run mono_3d_tracking.py TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'

### ISSUE THREAD

**Issue by kunshou123** [ucbdrive/3d-vehicle-tracking#21]
hi ,I run mono_3d_tracking.py  
/home/work/3d-vehicle-tracking-master/3d-tracking/mono_3d_estimation.py gta test --data_split val --json_path /home/gejun/work/3d-vehicle-tracking-master/3d-tracking/data/gta5_tracking/val/label/rec_10090911_clouds_21h53m_x-968y-1487tox2523y214_bdd.json -j 2 -b 1 --n_box_limit 300 --resume ./checkpoint/616_gta_checkpoint_030.pth.tar
Using RoIAlign
=> Loading checkpoint './checkpoint/616_gta_checkpoint_030.pth.tar'
=> Successfully loaded checkpoint './checkpoint/616_gta_checkpoint_030.pth.tar' (epoch 30)
Reading /home/gejun/work/3d-vehicle-tracking-master/3d-tracking/data/gta5_tracking/val/label/rec_10090911_clouds_21h53m_x-968y-1487tox2523y214_bdd.json ...
Load single json file
Sequences [463] with total 463 frames
Input images are not normalized
Number of image to test: 463
0
1
Traceback (most recent call last):
  File "/home/gejun/work/3d-vehicle-tracking-master/3d-tracking/mono_3d_estimation.py", line 539, in <module>
    main()
  File "/home/gejun/work/3d-vehicle-tracking-master/3d-tracking/mono_3d_estimation.py", line 535, in main
    test_model(model, args)
  File "/home/gejun/work/3d-vehicle-tracking-master/3d-tracking/mono_3d_estimation.py", line 426, in test_model
    for i, (image, box_info) in enumerate(iter(test_loader)):
  File "/home/gejun/anaconda3/envs/pytorch041/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/gejun/anaconda3/envs/pytorch041/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'

Process finished with exit code 1
========================================
I find the code can iter 2 times normally ,then it broken ,can you give me some advice to solve it???
 for i, (image, box_info) in enumerate(iter(test_loader)):
        # measure data loading time
        data_time.update(time.time() - end)
        end = time.time()

        with torch.no_grad():
            box_output, targets = model(image, box_info, args.device, 'test')

        batch_time.update(time.time() - end)
=======================================================

**Comment by eborboihuc** [comment]
Hi @kunshou123, this could be the problem of JSON files. Can you delete all the annotations and generate them again? The problem could be solved I think.
I'll just close this issue now. If you are facing the same problem after re-generation, please feel free to re-open this issue
