### ISSUE TITLE
RuntimeError: CUDA error: out of memory, possible to reduce memory requirement?

### ISSUE THREAD

**Issue by pinjiang** [ucbdrive/3d-vehicle-tracking#22]
I encountered same problem indicated in https://github.com/ucbdrive/3d-vehicle-tracking/issues/18. The pretrained model requires more than 8 Gbytes GPU memory. 

I don't have any GPU card more than 8 GBtyes at hand, but multiple cards <= 8 Gbytes. Is it possible to retrain the model to reduce the memory footprint?  > 8 Gbytes memory requirement is a bit high for inference only.

**Comment by eborboihuc** [comment]
Hi @pinjiang, thanks for open this issue.

Unfortunately, the support of improvement in memory requirement of faster-rcnn is beyond our scope. I would suggest you using other detectors to generate the results of the same format, or you can also use the generated detection result we provide.
