### ISSUE TITLE
How about the 3d detection AP?

### ISSUE THREAD

**Issue by xmyqsh** [ucbdrive/3d-vehicle-tracking#24]
It is a good work, accurate and efficient!

How about the 3d detection AP?

I want to know the relationship between the 3d tracking metric and the 3d detection metric.
As we can see, the threshold of 3d tracking iou is 0.25.

I want to know how much 3d detection leverage could be got from tracking.
As we can see, camera has surpassed lidar on 3d tracking task totally.

**Comment by eborboihuc** [comment]
Hi @xmyqsh, Thank you for the question!

In the recently released dataset (e.g., nuScenes, Argoverse, Waymo) they have different metrics for evaluation. Centroid-based favor more on the 3D detection-tracking balance; IoU-based metrics favor more on the accurate 3D detection. Usually, the better recall of the 3D detection can lead to better 3D tracking results. But it really depends on the tracking algorithms, evaluation metrics, and detection-tracking pipeline.

I believe there would be tons of discussion about the LiDAR and Camera-based method. So I won't stop on this here.
