### ISSUE TITLE
3d tracking benchmarking

### ISSUE THREAD

**Issue by bilalsattar** [ucbdrive/3d-vehicle-tracking#31]
I am able to achieve published results for 2d tracking. But, when I try to use 3d coordinates for 3d benchmarking using 3d iou in camera frame, I get too many false positives and mota becomes negative. can you point any issue with using 3d tracks? 

I used 3d benchmark provided by [https://github.com/xinshuoweng/AB3DMOT](url)

**Comment by bilalsattar** [comment]
Kitti training video 0001

![Screenshot from 2020-05-21 18-18-33](https://user-images.githubusercontent.com/40235535/82580744-e0101380-9b8f-11ea-894e-3f9f380f41db.png)

You can clearly see the mismatch between dotted ground truth and solid predictions.

**Comment by eborboihuc** [comment]
Hi @bilalsattar, thanks for the figure and great question.

I think it's reasonable. Our work using a monocular camera as the visual input (per frame) to estimate the 3D bounding boxes. We are doing great for near vehicles. On the other hand, even a stereo camera setting can have a hard time in the 40-80m range. It would definitely produce reasonable errors for a monocular setting. 

We found out that our 3D tracking pipeline helps 2D association and vice versa. Even today, our work stayed state-of-the-art results (top 10) on the [KITTI benchmark](http://www.cvlibs.net/datasets/kitti/eval_tracking_detail.php?result=85cec6cbe1e57d5a4645b16e13e1709bb9d677f0).

Lastly, we encourage you to take a look at our new work using quasi-dense representation learning with more robust 3D estimation on bigger datasets (e.g., nuScenes, Waymo). Please have a look [here](https://github.com/SysCV/qd-3dt).
