### ISSUE TITLE
checkpoint issue

### ISSUE THREAD

**Issue by FrankCAN** [ucbdrive/3d-vehicle-tracking#33]
Hi, thanks for your great work, but I got a problem when I use your provided checkpoint 616_gta_checkpoint_030.pth.tar, the detailed error is as below, thanks for your help.

RuntimeError: Error(s) in loading state_dict for DataParallel:
	Unexpected key(s) in state_dict: "module.base.base.base_layer.1.num_batches_tracked", "module.base.base.level0.1.num_batches_tracked", "module.base.base.level1.1.num_batches_tracked", "module.base.base.level2.tree1.bn1.num_batches_tracked", "module.base.base.level2.tree1.bn2.num_batches_tracked", "module.base.base.level2.tree2.bn1.num_batches_tracked", "module.base.base.level2.tree2.bn2.num_batches_tracked", "module.base.base.level2.root.bn.num_batches_tracked", "module.base.base.level2.project.1.num_batches_tracked", "module.base.base.level3.tree1.tree1.bn1.num_batches_tracked", "module.base.base.level3.tree1.tree1.bn2.num_batches_tracked", "module.base.base.level3.tree1.tree2.bn1.num_batches_tracked", "module.base.base.level3.tree1.tree2.bn2.num_batches_tracked", "module.base.base.level3.tree1.root.bn.num_batches_tracked", "module.base.base.level3.tree1.project.1.num_batches_tracked", "module.base.base.level3.tree2.tree1.bn1.num_batches_tracked", "module.base.base.level3.tree2.tree1.bn2.num_batches_tracked", "module.base.base.level3.tree2.tree2.bn1.num_batches_tracked", "module.base.base.level3.tree2.tree2.bn2.num_batches_tracked", "module.base.base.level3.tree2.root.bn.num_batches_tracked", "module.base.base.level3.project.1.num_batches_tracked", "module.base.base.level4.tree1.tree1.bn1.num_batches_tracked", "module.base.base.level4.tree1.tree1.bn2.num_batches_tracked", "module.base.base.level4.tree1.tree2.bn1.num_batches_tracked", "module.base.base.level4.tree1.tree2.bn2.num_batches_tracked", "module.base.base.level4.tree1.root.bn.num_batches_tracked", "module.base.base.level4.tree1.project.1.num_batches_tracked", "module.base.base.level4.tree2.tree1.bn1.num_batches_tracked", "module.base.base.level4.tree2.tree1.bn2.num_batches_tracked", "module.base.base.level4.tree2.tree2.bn1.num_batches_tracked", "module.base.base.level4.tree2.tree2.bn2.num_batches_tracked", "module.base.base.level4.tree2.root.bn.num_batches_tracked", "module.base.base.level4.project.1.num_batches_tracked", "module.base.base.level5.tree1.bn1.num_batches_tracked", "module.base.base.level5.tree1.bn2.num_batches_tracked", "module.base.base.level5.tree2.bn1.num_batches_tracked", "module.base.base.level5.tree2.bn2.num_batches_tracked", "module.base.base.level5.root.bn.num_batches_tracked", "module.base.base.level5.project.1.num_batches_tracked", "module.base.dla_up.ida_0.proj_1.1.num_batches_tracked", "module.base.dla_up.ida_0.node_1.1.num_batches_tracked", "module.base.dla_up.ida_1.proj_1.1.num_batches_tracked", "module.base.dla_up.ida_1.proj_2.1.num_batches_tracked", "module.base.dla_up.ida_1.node_1.1.num_batches_tracked", "module.base.dla_up.ida_1.node_2.1.num_batches_tracked", "module.dim.1.num_batches_tracked", "module.dim.4.num_batches_tracked", "module.dim.7.num_batches_tracked", "module.rot.1.num_batches_tracked", "module.rot.4.num_batches_tracked", "module.rot.7.num_batches_tracked", "module.dep.1.num_batches_tracked", "module.dep.4.num_batches_tracked", "module.dep.7.num_batches_tracked".

**Comment by eborboihuc** [comment]
It's about PyTorch's DataParallel scheme. It might be the case that you use a different PyTorch version other than the one used in this repo.
