### ISSUE TITLE
tracker models training processing issue

### ISSUE THREAD

**Issue by FrankCAN** [ucbdrive/3d-vehicle-tracking#35]
Hi, thanks for your great work, but how can I train the tracker models, such as LSTM, LSTMKF? On the code, I only found 803_kitti_300_linear.pth checkpoint for LSTM, but no 723_linear.pth for LSTMKF. So I just wonder how I can train them by myself.

Besides, many tracking methods are mentioned as below, but it seems only LSTM method is available for just evaluation.

Many thanks for your help.

**Comment by eborboihuc** [comment]
Hi @FrankCAN, thank you for the inquiry about our LSTM training code!

Training script is provided in the [motion_lstm.py](https://github.com/ucbdrive/3d-vehicle-tracking/blob/master/3d-tracking/motion_lstm.py#L351). However, LSTMKF is not available. It's just one experimental feature we didn't include in the final paper. Also, the training script might need some tweaking of the generated results from detector output.

We encourage you to take a look at our new method using quasi-dense representation and a more robust geometry relationship. Please have a look [here](https://github.com/SysCV/qd-3dt).
