### ISSUE TITLE
Where unzip the dataset.

### ISSUE THREAD

**Issue by TheLastImperial** [ucbdrive/3d-vehicle-tracking#38]
I use the next command to download the dataset.

```python
python loader/download.py mini
```

That download the next zip files

![Screenshot from 2020-08-31 12-27-13](https://user-images.githubusercontent.com/17633123/91753580-5821a880-eb85-11ea-8cc2-88466b173bc5.png)

When I run the command 

```bash
./faster-rcnn.pytorch/run_train.sh
```

and get the next error

```bash
Loaded dataset `gta_det_train` for training
Set proposal method: gt
Preparing training data...
done
before filtering, there are 0 images...
after filtering, there are 0 images...
0 roidb entries
Loading pretrained weights from data/pretrained_model/resnet101_caffe.pth
Traceback (most recent call last):
  File "trainval_net.py", line 445, in <module>
    epoch, step))
NameError: name 'step' is not defined
root : 201_14_18895 Finish!
```

This happened too when I try to run the `gen_dataset.py`

```python
PYTHONPATH=. python loader/gen_dataset.py gta val
```

and this give the error:

```bash
AssertionError: Not label files found in /workspace/3d-vehicle-tracking/3d-tracking/data/gta5_tracking/val/label
```

I suppose that this happened because the dataset has not been unzipped. But I don't know where to do this.
I unzip the files `gta_3d_tracking_val_image_0001.zip` and `gta_3d_tracking_val_label_0001.zip` in the directory `3d-tracking/data/gta5_tracking/val/{image,label}` but that problem continue.

Thanks.

**Comment by yangyiny** [comment]
you should unzip all the files to the correct positions

**Comment by eborboihuc** [comment]
Hi @TheLastImperial, have you solve the problem? 
Please unzip all the zip files you downloaded to the [designated location](https://github.com/ucbdrive/3d-vehicle-tracking/blob/master/3d-tracking/scripts/init.sh#L12-L20) and you may found it working. Just following the [readme](https://github.com/ucbdrive/3d-vehicle-tracking/tree/master/3d-tracking#quick-start) ```GTA Dataset Download and extract our GTA dataset and put it under ./3d-tracking/data/gta5_tracking/{split}/{type}. Where split = {train, val, test} and type = {image, label}```

Thank you @yanganlan0310 for explaining!
