### ISSUE TITLE
AttributeError in gen_pred.py

### ISSUE THREAD

**Issue by gauhar107** [ucbdrive/3d-vehicle-tracking#4]
Hi, sorry I'm a freshman learning this. There are some errors occurred when I run this line:
"python loader/gen_pred.py gta val "
how can i fix it?

Load label file from path: /home/user/3d-vehicle-tracking/3d-tracking/loader/data/gta5_tracking/val/label
Traceback (most recent call last):
  File "gen_pred.py", line 191, in <module>
    main()
  File "gen_pred.py", line 186, in main
    ds = Dataset()
  File "gen_pred.py", line 110, in __init__
    assert len(self.data_path) == self.det_result.shape[0], \
AttributeError: 'Dataset' object has no attribute 'det_result

looking for your reply~

**Comment by eborboihuc** [comment]
Please place the downloaded detection results `gta_val_detections.pkl` under `{YOUR_FOLDER}/3d-vehicle-tracking/3d-tracking/data/gta5_tracking/`

I'll make an update regarding the assertion message in the future.

If this does not work, please feel free to re-open this issue.

Best,
Hou-Ning

**Comment by gauhar107** [comment]
i'm so sorry, i have place the results as you sais, but still show the same Error. 
i don't know where have i missed...

**Comment by eborboihuc** [comment]
Can you post the steps you did after cloning this repository? For example, you may follow how others asked in this [Issue](https://github.com/ucbdrive/3d-vehicle-tracking/issues/3#issue-455657033).

Or, you may also want to follow the guide [here](https://github.com/ucbdrive/3d-vehicle-tracking/tree/master/3d-tracking#data-preparation) to try it again.

I'd recommend following the instruction again and post here if anything goes wrong.

**Comment by gauhar107** [comment]
Thank you so much!！！
Actually， after downloaded the whole ‘val’ dataset, and set them in correct path,  I solved the problem.
In addition，I want to know I have only one gpu, can I run run_tracking.py correctly?  Is there any code need to change?

**Comment by eborboihuc** [comment]
Please use `--gpu 0` flag to indicate which GPU you want to use.

Best!
