### ISSUE TITLE
how to apply the code into gta train dataset?

### ISSUE THREAD

**Issue by tt8cactus** [ucbdrive/3d-vehicle-tracking#40]
Hi, I'm a totally newb here.
I want to run your model on gta train set. 
However, it is too big! 300G+! 
So,it there any way to train the model  without RAM>300G?
appreciate a lot for your work!

**Comment by tt8cactus** [comment]
and i've run the model on gta val set,
however, the results are not as good as yours
is there anything else i can do except runing the pipeline given in README.md?
thanks a lot again!

**Comment by eborboihuc** [comment]
Hi @tt8cactus, thank you for bringing up this question.

I cannot help you to solve the RAM or memory issue. However, you may give a finer slice of the training data each time, feed in a smaller chunk, and release the old one when the iteration is finished.

We also encourage you to have a look at our new method with quasi-dense representation [here](https://github.com/SysCV/qd-3dt).
