### ISSUE TITLE
Errnor in Step 01 - 3D Estimation

### ISSUE THREAD

**Issue by yangyiny** [ucbdrive/3d-vehicle-tracking#42]
in Step 01 - 3D Estimation
when I run:
" python run_estimation.py gta val --session 616 --epoch 030"
I occur the problems :
 [Errno 2] No such file or directory: 'output/616_030_gta_val_set/616_030_rec_10090911_clouds_21h53m_x-968y-1487tox2523y214_bdd_roipool_output.pkl'

I can not find this file in my computer, what should I do?
thank  you !

**Comment by eborboihuc** [comment]
Hi @yanganlan0310, thank you for trying out our repo.
I suspect that the folder is not well-established according to this [code block](https://github.com/ucbdrive/3d-vehicle-tracking/blob/master/3d-tracking/run_estimation.py#L71-L73). May you check if the `output/` or `output/616_030_gta_val_set/` is built? 

Following the step in the readme seems to work for me. If you still find it hard to solve, please reopen this thread. Thanks.
