### ISSUE TITLE
Usage for custom image

### ISSUE THREAD

**Issue by DaraOrange** [ucbdrive/3d-vehicle-tracking#43]
Hello! Can you provide some instructions for usage of your model for custom image?

**Comment by eborboihuc** [comment]
Hi @DaraOrange, thanks for your interest in our work.

To apply our model to custom video or image sequences, we need to create a [KITTI-like dataset loader](https://github.com/ucbdrive/3d-vehicle-tracking/blob/master/3d-tracking/loader/gen_dataset.py#L298) to load in your data. The input needs to have a sequence of images and the corresponding camera poses. Of course, you may also use an off-the-shelf [visual odometry estimator](https://github.com/avisingh599/mono-vo) to estimate the camera poses.
Then it's easy to go with the pipeline with your own custom data.
