### ISSUE TITLE
Hi congratulations for your work, could your work be applied to cross-camera tracking?

### ISSUE THREAD

**Issue by dongxuemin666** [ucbdrive/3d-vehicle-tracking#44]

**Comment by eborboihuc** [comment]
Hi @dongxuemin666, thanks for the question. Unfortunately, we don't support cross-camera tracking in our ICCV implementation. 
Cross-camera tracking needs a robust high-level representation and geometrical-sound matching, or Re-ID module. We encourage you to check our new work at https://github.com/SysCV/qd-3dt about quasi-dense representation learning. It's the very first step to apply to cross-camera tracking.

**Comment by dongxuemin666** [comment]
Thanks for your reply
