### ISSUE TITLE
Dataset Details

### ISSUE THREAD

**Issue by NagabhushanSN95** [ucbdrive/3d-vehicle-tracking#45]
Hi,
Can you please specify what all ground truth data is available in the database you've collected? I'm looking for a synthetic or graphically rendered database with ground truth depth, camera pose and intrinsic. Are these available in your dataset?

**Comment by eborboihuc** [comment]
Hi @NagabhushanSN95, we collected the GTA dataset with ground truth object track id, object location (can infer object depth), camera pose, and (virtual) camera intrinsic, and more. Please feel free to check an example from our validation set by downloading via https://github.com/ucbdrive/3d-vehicle-tracking/blob/master/3d-tracking/loader/download.py

**Comment by NagabhushanSN95** [comment]
Hi @eborboihuc,  thanks for the quick reply. I downloaded the mini set from validation. I found images, camera intrinsic and pose. However, I didn't find depth maps. Is the available depth map dense or is it a single value per object? 

Can you kindly point me to where I can find the depth maps?

**Comment by eborboihuc** [comment]
Yeah, you're right. It's a single value per object in the released dataset. The depth maps are not included, unfortunately.

**Comment by NagabhushanSN95** [comment]
Okay, thank you!
