### ISSUE TITLE
cudaCheckError() failed : no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by FCInter** [ucbdrive/3d-vehicle-tracking#5]
This is the configuration of my system:
python3.5.2
cuda 9.0
pytorch 0.4.1
Tesla V100

Following the [README.md](https://github.com/ucbdrive/3d-vehicle-tracking/blob/master/README.md), I finish everything until `# Step 01 - 3D Estimation`, i.e. running the following command:

`python run_estimation.py gta val --session 616 --epoch 030`

It reported the following error message

`cudaCheckError() failed : no kernel image is available for execution on the device`

I learned that it was possibly caused by the configuration of the makefile. Since when I was running the test case in the `faster-rcnn.pytorch` folder, the same error happened. And by adding `-gencode arch=compute_70,code=sm_70` to the `lib/make.sh`, I solved this problem.

However, in `3d-tracking`, I did the same thing but the problem was not solved.

How shall I deal with this case?

Thanks!

The full printed message for this error is as follows:

```
0 2 python mono_3d_estimation.py gta test --data_split val --resume ./checkpoint/616_gta_checkpoint_030.pth.tar --json_path ./data/gta5_tracking/val/label/rec_10090911_clouds_21h53m_x-968y-1487tox2523y214_bdd.json --track_name 616_030_gta_val_set/616_030_rec_10090911_clouds_21h53m_x-968y-1487tox2523y214_bdd_roipool_output.pkl --session 616 -j 4 -b 1 --n_box_limit 300 --start_epoch 030
0.4.1
mono_3d_estimation.py gta test --data_split val --resume ./checkpoint/616_gta_checkpoint_030.pth.tar --json_path ./data/gta5_tracking/val/label/rec_10090911_clouds_21h53m_x-968y-1487tox2523y214_bdd.json --track_name 616_030_gta_val_set/616_030_rec_10090911_clouds_21h53m_x-968y-1487tox2523y214_bdd_roipool_output.pkl --session 616 -j 4 -b 1 --n_box_limit 300 --start_epoch 030
Using RoIAlign
=> Loading checkpoint './checkpoint/616_gta_checkpoint_030.pth.tar'
=> Successfully loaded checkpoint './checkpoint/616_gta_checkpoint_030.pth.tar' (epoch 30)
Reading ./data/gta5_tracking/val/label/rec_10090911_clouds_21h53m_x-968y-1487tox2523y214_bdd.json ...
Load single json file
Sequences [463] with total 463 frames
Input images are not normalized
Number of image to test: 463
cudaCheckError() failed : no kernel image is available for execution on the device
```

**Comment by eborboihuc** [comment]
Hi @FCInter,

Thanks for pointing out the architecture issue and the solution.

For the `cudaCheckError() failed: no kernel image is available for execution on the device` error; however, I cannot reproduce it on my end. How many GPUs do you use when running the code?

Could you try to add `--gpu 0` at the end of the line?
```python run_estimation.py gta val --session 616 --epoch 030 --gpu 0 ```

Thanks!

**Comment by eborboihuc** [comment]
I'm closing this issue because it has been inactive for a long while. Please feel free to reopen it.
