### ISSUE TITLE
Can't get GTA val set

### ISSUE THREAD

**Issue by ailovejinx** [ucbdrive/3d-vehicle-tracking#54]
When I'm in Data Preparation step, after I run the following code:
`python loader/download.py mini`
I got a result:
```
Connecting to dl.yf.io (dl.yf.io)|128.32.162.150|:80... --2022-10-27 17:46:01--  (try: 3)  http://dl.yf.io/bdd-data/3d-vehicle-tracking/label/gta_3d_tracking_val_label_0001.zip
Connecting to dl.yf.io (dl.yf.io)|128.32.162.150|:80... failed: Unknown error.
Retrying.

failed: Unknown error.
Retrying.

failed: Unknown error.
Retrying.
```

Is there something wrong with my Internet or VPN? How can I get this GTA dataset?

**Comment by Shinkair** [comment]
> 

Hi, I've met the same problem. Have u download successfully ever? Would u like try to share them throw Netdisk or other ways. 
I found it was sooo slowly download through http://dl.yf.io/bdd-data/3d-vehicle-tracking/

**Comment by ailovejinx** [comment]
Sry, I think you just have to wait for some time. I also found it downloading to slow so I interrupted it and delete all of them. 😕
