### ISSUE TITLE
What is the meaning of external parameter annotation in GTA data set?

### ISSUE THREAD

**Issue by lhenin** [ucbdrive/3d-vehicle-tracking#6]
Hi :
Can you explain what this parameter location and rotation means in extrinsics ?
Why is each picture different?Where is the origin of the world coordinates?

**Comment by lhenin** [comment]
How do I know the extrinsics parameters of the current frame in a static state? Instead of the extrinsics parameters relative to the previous frame?

**Comment by lhenin** [comment]
What is the height of the starting frame camera?

**Comment by eborboihuc** [comment]
Hi @lhenin,

The camera extrinsic is in the GPS coordinates. The origin of the coordinates is where the camera locates in the first frame of each sequence. It is the absolute camera pose to the origin. The height of the camera is 0.8 meters according to my colleague.

Best!
